version: '3.3'

services:

  application:
    image:
      statements-service-image
    container_name:
      statements-service-container
    ports:
      - 8080:8080
    depends_on:
      - database
      - redis
      - rabbitmq3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/statements_service_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=poiuyt09
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: statements_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poiuyt09
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      redis
    container_name:
      redis
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  rabbitmq3:
    image:
      rabbitmq:management
    container_name:
      rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pgdata:
    external: true
  redis-volume:
    external: true
